site_name: Daniel Wants To Be A DevOps
site_description: Documentation for my projects and other stuff I find useful
site_author: Daniel Beilin
# site_url:
repo_url: https://github.com/dbeilin/Wannabe-DevOps
repo_name:  dbeilin/Wannabe-DevOps

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    primary: indigo
    scheme: slate

plugins:
  # - glightbox
  - search:
      lang: en
  - tags:
      enabled: true
      tags_slugify_separator: "-"
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dbeilin

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-beilin/

  generator: false

copyright: Copyright &copy; 2024 Daniel Beilin

# extra_css:
#   - stylesheets/extra.css
